import express from "express";
import { createServer } from "node:http";
// @ts-expect-error Generated by the Vercel build command.
import { configureApp } from "./dist/vercel-server.js";

const app = express();
await configureApp(app, createServer(app));

export default app;
