CREATE TABLE `willAssetScans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`docType` enum('bank_balance','real_estate_registry','stock_certificate','insurance_policy','bond_certificate','pension_statement','vehicle_registration','business_registration','loan_statement','other') NOT NULL DEFAULT 'other',
	`docTypeLabel` varchar(64),
	`issuer` varchar(128),
	`ownerName` varchar(64),
	`assetName` varchar(256),
	`assetCode` varchar(128),
	`amount` varchar(64),
	`unit` varchar(32),
	`referenceDate` varchar(32),
	`location` text,
	`area` varchar(64),
	`beneficiary` varchar(128),
	`additionalInfo` text,
	`confidence` varchar(16) DEFAULT 'medium',
	`imageKey` varchar(512),
	`imageUrl` varchar(1024),
	`userMemo` text,
	`estimatedValue` bigint,
	`status` enum('pending','done','error') DEFAULT 'pending',
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `willAssetScans_id` PRIMARY KEY(`id`)
);
