CREATE TABLE `aiPrompts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mode` enum('public','general','legal','autobiography','diary','letter') NOT NULL,
	`title` varchar(100) NOT NULL,
	`description` varchar(300),
	`systemPrompt` text NOT NULL,
	`aiModel` varchar(100) NOT NULL DEFAULT 'default',
	`aiProvider` varchar(50) NOT NULL DEFAULT 'manus',
	`isActive` tinyint NOT NULL DEFAULT 1,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `aiPrompts_id` PRIMARY KEY(`id`),
	CONSTRAINT `aiPrompts_mode_unique` UNIQUE(`mode`)
);
--> statement-breakpoint
CREATE TABLE `expertPartners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`nameEn` varchar(100),
	`specialty` enum('lawyer','tax') NOT NULL DEFAULT 'lawyer',
	`subSpecialty` varchar(200),
	`country` varchar(8) NOT NULL DEFAULT 'KR',
	`city` varchar(100),
	`firmName` varchar(200),
	`bio` text,
	`bioEn` text,
	`yearsOfExperience` int DEFAULT 0,
	`languages` varchar(200),
	`email` varchar(320),
	`phone` varchar(50),
	`website` varchar(500),
	`photoUrl` varchar(1000),
	`licenseNumber` varchar(100),
	`status` enum('pending','active','suspended','rejected') NOT NULL DEFAULT 'pending',
	`annualFeePaid` int NOT NULL DEFAULT 0,
	`annualFeeExpiresAt` timestamp,
	`userId` int,
	`isSample` int NOT NULL DEFAULT 0,
	`ratingAvg` int DEFAULT 0,
	`reviewCount` int DEFAULT 0,
	`consultCount` int DEFAULT 0,
	`adminNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expertPartners_id` PRIMARY KEY(`id`)
);
